services:
  web:
    env_file: .env
    build:
      context: .
      args:
        - GO_VERSION=${GO_VERSION}
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: rebuild
          path: .
          target: /backend
